config/routes.rb
Portfolio::Application.routes.draw do

  root "pages#flightlog"
  get "/:map_id.:extension" => "pages#flightlog", as: :root_path

  # Users:
  resources :users

  # Sessions:
  resources :sessions, only: [:new, :create, :destroy]
  get    "/signup" => "users#new"
  get    "/login"  => "sessions#new"
  delete "/logout" => "sessions#destroy"

  # Flights:
  get   "/flights/new-flight-menu/(trip/:trip_id)" => "flights#new_flight_menu", as: :new_flight_menu
  post  "/flights/new-flight-menu/(trip/:trip_id)" => "flights#change_trip",    as: :change_new_flight_trip
  match "/flights/new/"                            => "flights#new", via: [:get, :post], as: :new_flight
  get   "/flights(/:map_id.:extension)" => "flights#index"
  resources :flights, except: [:index, :new]
  get   "/flights/:id(/:map_id.:extension)"        => "flights#show"
  get   "/flights/from/:start_date/to/:end_date(/:map_id.:extension)"   => "flights#show_date_range",  as: :show_date_range
  get   "/flights/year/:year(/:map_id.:extension)" => "flights#show_date_range", as: :show_year

  # Trips:
  resources :trips, except: [:show]
  get   "/trips/:id(/:map_id.:extension)"          => "trips#show"
  get   "/trips/:trip/section/:section(/:map_id.:extension)" => "trips#show_section", as: :show_section

  # Airports:
  get   "/airports(/:map_id.:extension)"     => "airports#index"
  resources :airports, except: [:index, :show]
  get   "/airports/:id(/:map_id.:extension)" => "airports#show"

  # Airlines and operators:
  resources :airlines
  get   "/airlines/:id(/:map_id.:extension)" => "airlines#show"
  get   "/operators/:operator(/:map_id.:extension)" => "airlines#show_operator", as: :show_operator
  get   "/operators/:operator/:fleet_number(/:map_id.:extension)" => "airlines#show_fleet_number", as: :show_fleet_number

  # Aircraft families and types:
  get   "/aircraft/new(/family/:family_id)"    => "aircraft_families#new",      as: :new_aircraft_family
  resources :aircraft_families, path: :aircraft, except: [:new]
  get   "/aircraft/:id(/:map_id.:extension)" => "aircraft_families#show"

  # Travel classes:
  get   "/classes"                           => "flights#index_classes"
  get   "/classes/:travel_class(/:map_id.:extension)" => "flights#show_class",  as: :show_class

  # Tail numbers:
  get   "/tails"                             => "flights#index_tails"
  get   "/tails/:tail_number(/:map_id.:extension)" => "flights#show_tail",      as: :show_tail

  # Flight routes:
  resources :routes, only: [:update]
  get   "/routes"                            => "routes#index"
  get   "/routes/:airport1/:airport2(/:map_id.:extension)" => "routes#show",    as: :show_route
  get   "/routes/edit/:airport1/:airport2"   => "routes#edit",                  as: :edit_route
  get   "/routes/:route" => redirect("routes", status: 301) # Redirect legacy routes to Index Routes

  # Boarding pass import pages:
  resources :p_k_passes, only: [:destroy]

  # Boarding pass parser pages:
  get   "/boarding-pass" => "flights#input_boarding_pass"
  get   "/boarding-pass/build" => "flights#build_boarding_pass", as: :build_boarding_pass
  get   "/boarding-pass/results/:data" => "flights#show_boarding_pass", as: :show_boarding_pass
  get   "/boarding-pass/json(/:callback)/:data" => "flights#show_boarding_pass_json", as:
   :show_boarding_pass_json

  # Admin pages:
  get   "/admin"                         => "admin#admin", as: :admin
  get   "/admin/airport-first-visits"    => "admin#airport_first_visits",    as: :airport_first_visits
  get   "/admin/annual-summary"          => "admin#annual_flight_summary",   as: :annual_flight_summary
  get   "/admin/boarding-pass-validator" => "admin#boarding_pass_validator", as: :boarding_pass_validator

  # API:
  get "api" => "api#index"
  get "api/annual_flight_summary"
  get "api/all_flights"
  get "api/recent_flights"

  # Certbot:
  get "/.well-known/acme-challenge/:id" => "pages#letsencrypt"

end

app/models/flight.rb
# Defines a model for flights.
class Flight < ApplicationRecord
  belongs_to :trip
  belongs_to :origin_airport, :class_name => "Airport"
  belongs_to :destination_airport, :class_name => "Airport"
  belongs_to :airline
  belongs_to :aircraft_family, :optional => true
  belongs_to :operator, :class_name => "Airline", :optional => true
  belongs_to :codeshare_airline, :class_name => "Airline", :optional => true
  
  # Form fields which should be saved as nil when the field is blank.
  NULL_ATTRS = %w( flight_number aircraft_name tail_number travel_class comment fleet_number boarding_pass_data )
  # Form fields which should be saved with leading and trailing whitespace
  # removed.
  STRIP_ATTRS = %w( operator fleet_number aircraft_family aircraft_name tail_number )
  # Form fields which should be saved capitalized and with all non-alphanumeric
  # characters removed.
  SIMPLIFY_ATTRS = %w( tail_number )

  # Warning text for if departure date and departure UTC might be too far apart
  WARNING_DEPARTURE_DATE_DEPARTURE_UTC_TOO_FAR = ActionController::Base.helpers.sanitize("Your departure date and UTC time are more than a day apart &ndash; are you sure they&rsquo;re correct?")
  
  before_save :nil_if_blank
  before_save :strip_blanks
  before_save :simplify_tail
  
  validates :origin_airport_id, :presence => true
  validates :destination_airport_id, :presence => true
  validates :trip_id, :presence => true
  validates :trip_section, :presence => true
  validates :departure_date, :presence => true
  validates :departure_utc, :presence => true
  validates :airline_id, presence: true
  validates :travel_class, :inclusion => { in: TravelClass::CLASSES.keys, message: "%{value} is not a valid travel class" }, :allow_nil => true, :allow_blank => true
  
  # Sorts Flights chronologically.
  # @method chronological()
  # @scope instance
  # @return [Array<Flight>] Flights sorted by departure time (UTC)
  scope :chronological, -> {
    order(:departure_utc)
  }


  # Returns the {AircraftFamily} parent family for the Flight, and the
  # {AircraftFamily} child type for the Flight if available.
  #
  # @return [Hash<Symbol, AircraftFamily>] a hash containing the
  #   {AircraftFamily} parent family for the Flight, and the {AircraftFamily}
  #   child type for the Flight if available.
  def aircraft_family_and_type
    return nil unless aircraft_family
    return {family: aircraft_family} if aircraft_family.is_root_family?
    return {family: aircraft_family.parent, type: aircraft_family}
  end

  # Returns the {Airline} and flight number for the Flight.
  #
  # @return [String] the airline and flight number
  def name
    return self.airline.name + " " + self.flight_number.to_s
  end

  # Returns an array of FlightAware flight IDs for a Flight. If the Flight has
  # no FlightAware ID, returns an empty array.
  #
  # @return [Array<String>] an array of FlightAware flight IDs
  def fa_flight_ids_array
    return [] if self.fa_flight_id.blank?
    return self.fa_flight_id.split(",")
  end

  # Returns a hash of routes for a collection of flights with sorted pairs of
  # {Airport} IDs as keys and distances in miles as values.
  #
  # @scope instance
  # @return [Hash] A hash in the format [Integer airport_id, Integer airport_id] => Integer distance in miles
  def route_distances
    return self.class.route_distances
  end

  # Returns a hash of routes for a collection of flights with sorted pairs of
  # {Airport} IDs as keys and distances in miles as values.
  #
  # @scope instance
  # @return [Hash] A hash in the format [Integer airport_id, Integer airport_id] => Integer distance in miles
  def self.route_distances
    airport_ids = self.all.pluck(:origin_airport_id, :destination_airport_id).flatten.uniq
    
    routes = Route.where("airport1_id IN (:a_ids) OR airport2_id IN (:a_ids)", a_ids: airport_ids)   # Trying to select only the specific routes used creates stack depth issues, so this method compromises by selecting all routes which involve any of the Airports in any of the Flights.
    distances = routes.map{|r| [[r.airport1_id,r.airport2_id].sort, r.distance_mi]}.to_h

    return self.all.pluck(:origin_airport_id, :destination_airport_id).map{|pair| [pair.sort, distances[pair.sort]]}.to_h
  end

  # Return the longest and shortest flights from a collection of flights.
  #
  # Returns a hash with keys of :max, :min, and :zero, which contain the longest
  # Flight(s), shortest non-zero-length Flight(s), and zero-length Flight(s)
  # respectively. Each of these values is itself a hash, with an array of two
  # {Airport Airports} as each key, and the distance in statute miles as each
  # value.
  # 
  # Zero-length flights are strictly defined as flights where the origin and
  # destination airports are the same. Theoretically, if a flight were flown
  # between two airports that were less than 0.5 miles apart, then the flight
  # would be included in :min rather than :zero, even though its integer
  # distance would be rounded to zero.
  #
  # @scope instance
  # @return [Hash] A hash of superlative routes.
  # @example
  #   Flight.all.superlatives #=> {
  #     :max => {[Airport1,Airport2] => 8500},
  #     :min => {[Airport3,Airport4] => 50, [Airport5,Airport6] => 50},
  #     :zero => {[Airport7,Airport7] => 0}
  #   }
  def self.superlatives
    route_distances = self.all.route_distances
    
    # Separate out routes where both airports are the same:
    routes_zero, routes_non_zero = route_distances.partition{|k, v| k[0] == k[1]}
    routes_non_zero = routes_non_zero.to_h
    routes_zero = routes_zero.to_h

    distance_min, distance_max = routes_non_zero.values.compact.sort.values_at(0,-1)

    route_superlatives = Hash.new
    route_superlatives[:max] = routes_non_zero.select{|k, v| v == distance_max}
    route_superlatives[:min] = routes_non_zero.select{|k, v| v == distance_min}
    route_superlatives[:zero] = routes_zero

    # Convert airport IDs to airports:
    airport_ids = route_superlatives.values.map{|r| r.keys}.flatten.uniq
    airports = Airport.find(airport_ids).map{|a| [a.id, a]}.to_h
    
    return route_superlatives.map{|k,v| [k, v.map{|r| [[airports[r[0][0]], airports[r[0][1]]], r[1]] }.to_h ]}.to_h
  end

  # Returns the total distance in statute miles of a collection of Flights.
  # 
  # @scope instance
  # @param allow_unknown_distances [Boolean] If set to true, will consider
  #   Flights with unknown distances to have zero distance. If set to false,
  #   will return nil if any of the Flight distances are unknown.
  # @return [Integer, nil] the total distance of the Flights in statute miles
  def self.total_distance(allow_unknown_distances=true)
    route_distances = self.all.route_distances
    distances = self.all.pluck(:origin_airport_id, :destination_airport_id).map{|pair| route_distances[pair.sort]}
    if allow_unknown_distances || (distances.include?(nil) == false)
      return distances.reduce(0){|sum, d| sum + (d || 0)}
    else
      return nil
    end
  end

  # For a given flight collection, returns a range of the years that contain
  # flights.
  # 
  # @return [Range<Integer>] a range of years
  def self.year_range
    return nil unless self.any?
    sorted = self.chronological
    return sorted.first.departure_date.year..sorted.last.departure_date.year
  end

  # For a given flight collection, returns all years that have at least one
  # Flight.
  #
  # @return [Array<Integer>] the years having at least one Flight
  def self.years_with_flights
    flights = self.chronological
    years_with_flights = Array.new
    flights.each do |flight|
      years_with_flights.push(flight.departure_date.year)
    end
    return years_with_flights.uniq
  end
    
  protected
  
  # Converts blank form fields to nil before saving them to the database.
  #
  # @return [Hash]
  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end

  # Removes leading and trailing whitespace from form fields before saving them
  # to the database.
  #
  # @return [Hash]
  def strip_blanks
    STRIP_ATTRS.each { |attr| self[attr] = self[attr].strip if !self[attr].blank? }
  end
  
  # Capitalizes and removes non-alphanumeric characters from form fields before
  # saving them to the database.
  #
  # @return [Hash]
  def simplify_tail
    SIMPLIFY_ATTRS.each { |attr| self[attr] = TailNumber.simplify(self[attr]) if !self[attr].blank? }
  end
  
end

app/helpers/flights_helper.rb
# Defines helper methods for {Flight} views.
module FlightsHelper
  
  # Creates a nested list for an aircraft type and all of its parents.
  #
  # @param types [Array] the output of an {AircraftFamily#type_and_parent_types}
  #   call
  # @return [ActiveSupport::SafeBuffer, nil] a nested list of links to aircraft
  #   types
  def aircraft_type_tree(types, top_level=true)
    current = types.pop()

    ul_classes = ["aircraft-type-tree"]
    ul_classes.push("aircraft-type-tree-top") if top_level
    output = content_tag(:ul, class: ul_classes) do

      li_classes = (types.any? || top_level) ? nil : "current-type"
      content_tag(:li, class: li_classes) do

        concat link_to(current.full_name, aircraft_family_path(current.slug), title: "View flights on #{current.full_name} aircraft")

        if types.any?
          concat aircraft_type_tree(types, false)
        elsif current.icao_code.present?
          concat content_tag(:div, current.icao_code, class: "supplemental-code")
        end

      end
    end

    return output
  end

  # Accepts an icon type and an interpretation, and returns the text of the
  # interpretation, with an image_tag for an icon if appropriate. Used to
  # augment BCBP interpretations in a {BoardingPass} table, such as on
  # {FlightsController#show} or {FlightsController#show_boarding_pass}.
  #
  # @param icon_type [:airline, :airport, :selectee, :travel_class] whether this
  #   icon should be for an airline logo, airport country flag, TSA PreCheck
  #   selectee status, or travel class stars
  # @param interpretation [String, Hash, nil] The interpretation of what the raw
  #   value means. Can either be a string of the interpretation, or a hash with
  #   the interpretation string under the text key, and a slug for an icon under
  #   the icon_slug key.
  # @return [ActiveSupport::SafeBuffer, nil] interpretation text, with an an
  #   image tag for an icon if appropriate.
  #
  # @see BoardingPass
  def display_bcbp_interpretation(icon_type, interpretation)
    if interpretation.is_a?(Hash)
      icon_slug = interpretation[:icon_slug]
      interpretation = interpretation[:text]
    else
      icon_slug = nil
    end
    if icon_type
      icon = display_bcbp_icon(icon_type, interpretation, icon_slug)
      return interpretation unless icon
      return sanitize(interpretation) + content_tag(:div, icon, class: "interpreted-icon")
    else
      return interpretation
    end
  end

  # Accepts an icon type, interpretation, and icon slug, and returns an
  # image_tag for an icon.
  #
  # @param icon_type [:airline, :airport, :selectee, :travel_class] whether this
  #   icon should be for an airline logo, airport country flag, TSA PreCheck
  #   selectee status, or travel class stars
  # @param interpretation [String] The interpretation of what the raw
  # @param icon_slug [String] A unique identifier for an instance of this type
  #   of icon. (For example, an airline slug used to find an airline icon's
  #   filename.)
  # @return [ActiveSupport::SafeBuffer, nil] an image tag for the appropriate
  #   icon
  # 
  # @see #display_bcbp_interpretation
  def display_bcbp_icon(icon_type, interpretation, icon_slug)
    return nil unless icon_slug

    case icon_type
    when :airline
      return airline_icon(icon_slug, title: interpretation)
    when :airport
      return country_flag_icon(icon_slug)
    when :selectee
      if icon_slug == "LLLL"
        return image_tag("tpc.png", title: interpretation, class: "airline-icon")
      else
        return nil
      end
    when :travel_class
      return quality_stars(icon_slug)
    else
      return nil
    end
    return nil
  end
  
  # Renders a star rating image based on a number between 0 and 5, inclusive.
  # Used for visually depicting the quality of different {TravelClass
  # TravelClasses}.
  # 
  # @param quality [Integer] A number of stars rating (0 through 5, inclusive)
  # @param inline [:left, :right, :both, :nil] Defines whether the image is
  #   inline to the left of text, to the right of text, in between text, or not
  #   inline. Used to determine margin styles.
  # @return [ActiveSupport::SafeBuffer] an image_tag for a star rating
  def quality_stars(quality, inline: nil)
    quality = quality.to_i
    quality = 0 if quality < 0
    quality = 5 if quality > 5
    classes = %w(star-rating)
    inline_classes = {left: "icon-left", right: "icon-right", both: "icon-between-text"}
    classes.push(inline_classes[inline]) if inline_classes[inline]
    return image_tag("stars/#{quality}.svg", title: "#{quality} out of 5 stars", alt: "#{quality} out of 5 stars", class: classes.join(" "))
  end
end

app/views/flights/_bcbp.html.erb
<h2>Boarding Pass Data</h2>

<p><%= link_to "JSON output", show_boarding_pass_json_path(boarding_pass.raw) %></p>

<div id="flight-boarding-pass-data">
  <% boarding_pass.ordered_groups.each do |group| %>
    <h3><%= group[:title] %></h3>
    <%= render partial: "bcbp_group", locals: {group_fields: group[:fields]} %>
  <% end %>
</div>

app/views/flights/_flight_table.html.erb
<table class="flightlog" id="flight-table">
  <tr>
    <th class="counter">#</th>
    <th class="flight-flight">Flight</td>
    <th class="flight-route">Route</td>
    <th class="flight-date"><%= is_summary ? "Departure" : sort_link("Departure", :departure, :asc, "flight-list") %></th>
  </tr>

  <% flights.each_with_index do |flight, index| %>
    <% row_class = (index > 0 && flights[index-1].trip_id == flight.trip_id && flights[index-1].trip_section == flight.trip_section) ? "no-top-border" : "" %>
    <tr id="flight-row-<%= flight.id %>" class="<%= row_class %>">
	
      <td class="counter"><%= (@sort == [:departure, :desc]) ? flights.length - index : index + 1 %></td>
      
      <td class="flight-flight"><%= Trip::HIDDEN_MARKER if flight.trip.hidden %><%= link_to(airline_icon(flight.airline.slug, title: "View flight details for #{flight.airline.name} #{flight.flight_number.to_s}") + "#{flight.airline.name} #{flight.flight_number.to_s}", flight_path(flight), title: "View flight details for #{flight.airline.name} #{flight.flight_number.to_s}") %></td>
      <td class="flight-route">
        <%= (params[:controller] == "airports" && params[:action] == "show" && @airport.id == flight.origin_airport_id) ? code_mono(flight.origin_airport.iata_code) : link_to(code_mono(flight.origin_airport.iata_code), airport_path(flight.origin_airport.slug), title: "View airport details for #{flight.origin_airport.city}") %> <%= Route::ARROW_ONE_WAY_HTML %> <%= (params[:controller] == "airports" && params[:action] == "show" && @airport.id == flight.destination_airport_id) ? code_mono(flight.destination_airport.iata_code) : link_to(code_mono(flight.destination_airport.iata_code), airport_path(flight.destination_airport.slug), title: "View airport details for #{flight.destination_airport.city}") %>
      </td>
      <td class="flight-date"><%= NumberFormat.date(flight.departure_date) %></td>
      
    </tr>
  <% end %>

  <%= flight_table_total_row(flights) %>
</table>

app/views/flights/edit.html.erb
<% provide(:title, "Edit Flight") %>
<% provide(:button_text, "Update Flight") %>
<% add_breadcrumb "Flights", flights_path %>
<% add_breadcrumb "#{@flight.airline.name} #{@flight.flight_number}", flight_path(@flight) %>
<% add_breadcrumb "Edit Flight", edit_flight_path(@flight) %>

<h1>Edit Flight</h1>

<%= render partial: "form", locals: {flight: @flight, defaults: @defaults} %>

app/views/flights/show.html.erb
<% provide(:title, @flight.name) %>
<% provide(:meta_description, "Details for Paul Bogardʼs #{@flight.name} flight on #{NumberFormat.date(@flight.departure_date)}.") %>
<% add_admin_action link_to("Delete Flight", @flight, method: :delete, data: { confirm: "Are you sure you want to delete this flight?" }, class: "warning") %>
<% add_admin_action link_to("Edit Flight", edit_flight_path(@flight)) %>
<% add_breadcrumb "Flights", flights_path %>
<% add_breadcrumb @flight.name, flight_path(params[:id]) %>

<h1><%= @flight.airline.name %> <%= @flight.flight_number %></h1>

<% if @flight.comment %>
  <p class="comment"><%= @flight.comment %></p>
<% end %>

<table class="flight-large-route">
  <tr>
    <td class="flight-show-airport-flag">
      <%= country_flag_icon(@flight.origin_airport.country) %>
    </td>
    <td class="flight-show-airport-airplane-icon" rowspan="3">
      <%= image_tag("airplane.svg", width: 48) %>
    </td>
    <td class="flight-show-airport-flag">
      <%= country_flag_icon(@flight.destination_airport.country) %>
    </td>
  </tr>
  <tr>
    <td class="flight-show-airport-code">
      <%= @flight.origin_airport.iata_code %>
    </td>
    <td class="flight-show-airport-code">
      <%= @flight.destination_airport.iata_code %>
    </td>
  </tr>
  <tr>
    <td class="flight-show-airport-city" id="flight-origin-airport">
      <%= link_to(@flight.origin_airport.city, airport_path(@flight.origin_airport.slug), title: "View airport details for " + @flight.origin_airport.city) %>
    </td>
    <td class="flight-show-airport-city" id="flight-destination-airport">
      <%= link_to(@flight.destination_airport.city, airport_path(@flight.destination_airport.slug), title: "View airport details for " + @flight.destination_airport.city) %>
    </td>
  </tr>
</table>

<%= render(partial: "layouts/map", locals: {map: @maps[:flight_map]}) %>

<table class="flightlog">
  
  <tr>
    <td class="label-column">Departure Date</td>
    <td id="flight-departure-date"><%= NumberFormat.date(@flight.departure_date) %></td>
  </tr>
  <tr>
    <td class="label-column">Trip</td>
    <td id="flight-trip"><%= Trip::HIDDEN_MARKER if @flight.trip.hidden %><%= link_to(@flight.trip.name, trip_path(@flight.trip), title: "View trip details for " + @flight.trip.name) %> (<%= link_to("Section #{@flight.trip_section}", show_section_path(@flight.trip, @flight.trip_section), title: "View details for section #{@flight.trip_section} of #{@flight.trip.name}" ) %>)</td>
  </tr>
  <tr>
    <td class="label-column">Route</td>
    <td id="flight-route">
      <% if @route_distance %>
        <div class="supplemental-info" id="flight-route-distance"><%= NumberFormat.value(@route_distance) %> mi / <%= NumberFormat.value(Distance::km(@route_distance)) %> km</div>
      <% elsif logged_in? %>
        <div class="supplemental-info message-error"><%= link_to "Distance Undefined", edit_route_path(@flight.origin_airport,@flight.destination_airport) %></div>
      <% end %>
      <%= link_to(Route.airport_string(@flight.origin_airport, @flight.destination_airport, sort: false), show_route_path(airport1: @flight.origin_airport.slug, airport2: @flight.destination_airport.slug), title: "View flights between #{@flight.origin_airport.city} and #{@flight.destination_airport.city}") %>
    </td>
  </tr>
  <% if @flight.travel_class %>
  <tr>
    <td class="label-column">Travel Class</td>
    <td id="flight-travel-class">
			<%= quality_stars(TravelClass::CLASSES[@flight.travel_class][:quality], inline: :left) %><%= link_to(TravelClass::CLASSES[@flight.travel_class][:name].titlecase, show_class_path(@flight.travel_class), title: "View #{TravelClass::CLASSES[@flight.travel_class][:name].downcase} class flights") %>
			</td>
		</td>
  </tr>
  <% end %>
  <tr>
    <td class="label-column">Airline</td>
    <td id="flight-airline">
			<div class="supplemental-code"><%= @flight.airline.iata_code %></div>
			<%= link_to(airline_icon(@flight.airline.slug, title: @flight.airline.name) + @flight.airline.name, airline_path(@flight.airline.slug), title: "View flights on " + @flight.airline.slug) %>
			</td>
  </tr>
  <% if @flight.operator %>
  <tr>
    <td class="label-column">Operated By</td>
    <td id="flight-operator">
			<div class="supplemental-code"><%= @flight.operator.iata_code %></div>
			<%= link_to(airline_icon(@flight.operator.slug, title: @flight.operator.name) + @flight.operator.name, show_operator_path(@flight.operator.slug), title: "View flights operated by " + @flight.operator.name) %>
			<% if @flight.fleet_number %> (<%= link_to("#" + @flight.fleet_number, show_fleet_number_path(@flight.operator.slug, @flight.fleet_number), title: "View flights on #{@flight.operator.name} aircraft ##{@flight.fleet_number}") %>)<% end %>
			</td>
  </tr>
  <% end %>
  <% if @flight.codeshare_airline %>
  <tr>
    <td class="label-column">Codeshare</td>
    <td id="flight-codeshare">
			<div class="supplemental-code"><%= @flight.codeshare_airline.iata_code %></div>
			<%= airline_icon(@flight.codeshare_airline.slug, title: @flight.codeshare_airline.name) %><span id="flight-codeshare-airline"><%= @flight.codeshare_airline.name %></span> <span id="flight-codeshare-flight-number"><%= @flight.codeshare_flight_number %></span>
			</td>
		</td>
  </tr>
  <% end %>
  
  <% if @flight.aircraft_family %>
    <tr>
      <td class="label-column">Equipment</td>
      <td class="aircraft-type" id="flight-aircraft">
        <%= aircraft_type_tree(@flight.aircraft_family.type_and_parent_types) %>
      </td>
    </tr>
  <% end %>

  <% if @flight.aircraft_name %>
  <tr>
    <td class="label-column">Aircraft Name</td>
    <td class="aircraft-name" id="flight-aircraft-name"><%= @flight.aircraft_name %></td>
  </tr>
  <% end %>
  <% if @flight.tail_number %>
  <tr>
    <td class="label-column">Tail Number</td>
    <td class="tail-number" id="flight-tail-number"><%= tail_number_with_country_flag(@flight.tail_number, false) %></td>
  </tr>
  <% end %>
  <% if logged_in? && @flight.fa_flight_ids_array.any? %>
    <tr>
      <td class="label-column">FA Flight ID</td>
      <td id="flight-fa-flight-id"><% @flight.fa_flight_ids_array.each_with_index do |fa_flight_id, index| %>
        <%= fa_flight_id %><% if index < (@flight.fa_flight_ids_array.length - 1) %><br><% end %>
      <% end %></td>
    </tr>
  <% end %>
</table>

<% if logged_in? && @boarding_pass.data.present? %>
  <%= render partial: "bcbp", locals: {boarding_pass: @boarding_pass} %>
<% end %>

app/views/flights/show_boarding_pass.html.erb
<% provide(:title, "Boarding Pass Results") %>
<% provide(:meta_description, "Results from the boarding pass barcode parser.") %>
<% add_breadcrumb "Boarding Pass", boarding_pass_path %>
<% add_breadcrumb @results, boarding_pass_path %>

<h1>Boarding Pass Results</h1>

<div id="bcbp-input-form">
  <%= form_tag(build_boarding_pass_path, method: :get, id: "bcbp-form") do %>
  <p>
    <%= label :data, "Update your boarding pass data here:" %><br />
	  <%= text_area_tag :data, params[:data], size: "70x5", class: "code-mono" %>
  </p>
  <p><%= submit_tag "Update", name: nil, id: "bcbp_submit_button" %></p>
  
<% end %>
</div>

<% if @boarding_pass.data.present? %>
  <%= render partial: "bcbp", locals: {boarding_pass: @boarding_pass} %>
<% else %>
  <p>Weʼre sorry, but we were unable to parse the boarding pass data provided.</p>
<% end %>