config/routes.rb
Portfolio::Application.routes.draw do

  root "pages#flightlog"
  get "/:map_id.:extension" => "pages#flightlog", as: :root_path

  # Users:
  resources :users

  # Sessions:
  resources :sessions, only: [:new, :create, :destroy]
  get    "/signup" => "users#new"
  get    "/login"  => "sessions#new"
  delete "/logout" => "sessions#destroy"

  # Flights:
  get   "/flights/new-flight-menu/(trip/:trip_id)" => "flights#new_flight_menu", as: :new_flight_menu
  post  "/flights/new-flight-menu/(trip/:trip_id)" => "flights#change_trip",    as: :change_new_flight_trip
  match "/flights/new/"                            => "flights#new", via: [:get, :post], as: :new_flight
  get   "/flights(/:map_id.:extension)" => "flights#index"
  resources :flights, except: [:index, :new]
  get   "/flights/:id(/:map_id.:extension)"        => "flights#show"
  get   "/flights/from/:start_date/to/:end_date(/:map_id.:extension)"   => "flights#show_date_range",  as: :show_date_range
  get   "/flights/year/:year(/:map_id.:extension)" => "flights#show_date_range", as: :show_year

  # Trips:
  resources :trips, except: [:show]
  get   "/trips/:id(/:map_id.:extension)"          => "trips#show"
  get   "/trips/:trip/section/:section(/:map_id.:extension)" => "trips#show_section", as: :show_section

  # Airports:
  get   "/airports(/:map_id.:extension)"     => "airports#index"
  resources :airports, except: [:index, :show]
  get   "/airports/:id(/:map_id.:extension)" => "airports#show"

  # Airlines and operators:
  resources :airlines
  get   "/airlines/:id(/:map_id.:extension)" => "airlines#show"
  get   "/operators/:operator(/:map_id.:extension)" => "airlines#show_operator", as: :show_operator
  get   "/operators/:operator/:fleet_number(/:map_id.:extension)" => "airlines#show_fleet_number", as: :show_fleet_number

  # Aircraft families and types:
  get   "/aircraft/new(/family/:family_id)"    => "aircraft_families#new",      as: :new_aircraft_family
  resources :aircraft_families, path: :aircraft, except: [:new]
  get   "/aircraft/:id(/:map_id.:extension)" => "aircraft_families#show"

  # Travel classes:
  get   "/classes"                           => "flights#index_classes"
  get   "/classes/:travel_class(/:map_id.:extension)" => "flights#show_class",  as: :show_class

  # Tail numbers:
  get   "/tails"                             => "flights#index_tails"
  get   "/tails/:tail_number(/:map_id.:extension)" => "flights#show_tail",      as: :show_tail

  # Flight routes:
  resources :routes, only: [:update]
  get   "/routes"                            => "routes#index"
  get   "/routes/:airport1/:airport2(/:map_id.:extension)" => "routes#show",    as: :show_route
  get   "/routes/edit/:airport1/:airport2"   => "routes#edit",                  as: :edit_route
  get   "/routes/:route" => redirect("routes", status: 301) # Redirect legacy routes to Index Routes

  # Boarding pass import pages:
  resources :p_k_passes, only: [:destroy]

  # Boarding pass parser pages:
  get   "/boarding-pass" => "flights#input_boarding_pass"
  get   "/boarding-pass/build" => "flights#build_boarding_pass", as: :build_boarding_pass
  get   "/boarding-pass/results/:data" => "flights#show_boarding_pass", as: :show_boarding_pass
  get   "/boarding-pass/json(/:callback)/:data" => "flights#show_boarding_pass_json", as:
   :show_boarding_pass_json

  # Admin pages:
  get   "/admin"                         => "admin#admin", as: :admin
  get   "/admin/airport-first-visits"    => "admin#airport_first_visits",    as: :airport_first_visits
  get   "/admin/annual-summary"          => "admin#annual_flight_summary",   as: :annual_flight_summary
  get   "/admin/boarding-pass-validator" => "admin#boarding_pass_validator", as: :boarding_pass_validator

  # API:
  get "api" => "api#index"
  get "api/annual_flight_summary"
  get "api/all_flights"
  get "api/recent_flights"

  # Certbot:
  get "/.well-known/acme-challenge/:id" => "pages#letsencrypt"

end

app/views/admin/admin.html.erb
<% provide(:title, "Admin") %>
<% add_breadcrumb "Admin", admin_path %>

<h1>Admin</h1>

<ul>
  <li><%= link_to "Annual Flight Summary", annual_flight_summary_path %></li>
  <li><%= link_to "Boarding Pass Validator", boarding_pass_validator_path %></li>
  <li><%= link_to "Airport First Visits", airport_first_visits_path %></li>
</ul>

app/views/admin/airport_first_visits.html.erb
<% provide(:title, "Airport First Visits") %>
<% add_breadcrumb "Admin", admin_path %>
<% add_breadcrumb "Airport First Visits", airport_first_visits_path %>

<table class="flightlog">
  <tr>
    <th class="counter">Index</th>
    <th class="airport-code">Airport</th>
    <th class="flight-date">Departure</th>
    <th class="flight-route">Route</th>
    <th class="flight-flight">Flight</th>
  </tr>
<% prev_flight = nil %>
<% @airport_first_visits.each.with_index(1) do |(airport_id, flight), index| %>
  <% row_class = (flight == prev_flight) ? "no-top-border" : "" %>
  <tr class="<%= row_class %>">
    <td class="counter"><%= index %></td>
    <td class="airport-code code-mono"><%= link_to(@airports[airport_id][:iata_code], airport_path(@airports[airport_id][:slug])) %></td>
    <td class="flight-date"><%= NumberFormat.date(flight.departure_date) %></td>
    <td class="flight-route">
      <% classes_orig = flight.origin_airport.id == airport_id ? ["bold"] : [] %>
      <% classes_dest = flight.destination_airport.id == airport_id ? ["bold"] : [] %>
      <%= code_mono(flight.origin_airport.iata_code, classes: classes_orig) %>
      <%= Route::ARROW_ONE_WAY_HTML %>
      <%= code_mono(flight.destination_airport.iata_code, classes: classes_dest) %>
    </td>
    <td class="flight-flight"><%= link_to(airline_icon(flight.airline.slug, title: "View flight details for #{flight.airline.name} #{flight.flight_number.to_s}") + "#{flight.airline.iata_code} #{flight.flight_number.to_s}", flight_path(flight), title: "View flight details for #{flight.airline.name} #{flight.flight_number.to_s}") %></td>
  </tr>
  <% prev_flight = flight %>
<% end %>
</table>

app/views/admin/annual_flight_summary.html.erb
<% provide(:title, "Annual Flight Summary") %>
<% add_breadcrumb "Admin", admin_path %>
<% add_breadcrumb "Annual Flight Summary", annual_flight_summary_path %>

<h1>Annual Flight Summary</h1>

<h2>Flights</h2>
<table class="flightlog">
  <tr>
    <th class="annual-summary">Year</th>
    <th class="annual-summary">Business</th>
    <th class="annual-summary">Mixed</th>
    <th class="annual-summary">Personal</th>
    <th class="annual-summary annual-summary-undefined">Undefined</th>
    <th class="annual-summary">Total</th>
  </tr>
<% @annual_flight_summary.each do |year, data| %>
  <% row_count = data[:count].inject(0) { |sum, n| sum + n[1] } %>
  <tr>
    <td class="annual-summary"><%= year %></td>
    <td class="annual-summary"><%= data[:count][:business] %></td>
    <td class="annual-summary"><%= data[:count][:mixed] %></td>
    <td class="annual-summary"><%= data[:count][:personal] %></td>
    <td class="annual-summary annual-summary-undefined"><%= data[:count][:undefined] > 0 ? data[:count][:undefined] : "-"  %></td>
    <td class="annual-summary"><%= row_count %></td>
  </tr>
<% end %>
</table>

<h2>Distances</h2>
<table class="flightlog">
  <tr>
    <th class="annual-summary">Year</th>
    <th class="annual-summary">Business</th>
    <th class="annual-summary">Mixed</th>
    <th class="annual-summary">Personal</th>
    <th class="annual-summary annual-summary-undefined">Undefined</th>
    <th class="annual-summary">Total</th>
  </tr>
<% @annual_flight_summary.each do |year, data| %>
  <% row_miles = data[:distance_mi].inject(0) { |sum, n| sum + n[1] } %>
  <tr>
    <td class="annual-summary"><%= year %></td>
    <td class="annual-summary annual-summary-distance">
      <%= data[:distance_mi][:business] %> mi<br>
      <%= Distance.km(data[:distance_mi][:business]) %> km
    </td>
    <td class="annual-summary annual-summary-distance">
      <%= data[:distance_mi][:mixed] %> mi<br>
      <%= Distance.km(data[:distance_mi][:mixed]) %> km
    </td>
    <td class="annual-summary annual-summary-distance">
      <%= data[:distance_mi][:personal] %> mi<br>
      <%= Distance.km(data[:distance_mi][:personal]) %> km
    </td>
    <td class="annual-summary annual-summary-distance annual-summary-undefined">
      <% if data[:distance_mi][:undefined] > 0 %>
        <%= data[:distance_mi][:undefined] %> mi<br>
      <%= Distance.km(data[:distance_mi][:undefined]) %> km
      <% else %>
        -
      <% end %>
    </td>
    <td class="annual-summary annual-summary-distance">
      <%= row_miles %> mi<br>
      <%= Distance.km(row_miles) %> km
    </td>
  </tr>
<% end %>
</table>

app/views/admin/boarding_pass_validator.html.erb
<% provide(:title, "Boarding Pass Validator") %>
<% add_breadcrumb "Admin", admin_path %>
<% add_breadcrumb "Boarding Pass Validator", boarding_pass_validator_path %>

<h1>Baording Pass Validator</h1>

<h2>Invalid Passes</h2>
<table class="flightlog">
  <thead>
    <th>Boarding Pass Data</th>
    <th>Edit</th>
  </thead>
<% count = 0 %>
<% @pass_flights.each do |flight| %>
  <% pass = BoardingPass.new(flight.boarding_pass_data) %>
  <% unless pass.is_valid? %>
  <% count += 1 %>
  <tr>
    <td>
      <div style="width: 30em;">
        <%= render partial: "flights/bcbp_compact", locals: {boarding_pass: pass} %>
      </div>
    </td>
    <td>
      <%= link_to "Edit", edit_flight_path(flight.id) %>
    </td>
  </tr>
  <% end %>
<% end %>
  <tr>
    <td colspan="3" class="flightlog-total">
      <%= pluralize(NumberFormat.value(count), "invalid boarding pass") %>
    </td>
  </tr>
</table>