config/routes.rb
Portfolio::Application.routes.draw do

  root "pages#flightlog"
  get "/:map_id.:extension" => "pages#flightlog", as: :root_path

  # Users:
  resources :users

  # Sessions:
  resources :sessions, only: [:new, :create, :destroy]
  get    "/signup" => "users#new"
  get    "/login"  => "sessions#new"
  delete "/logout" => "sessions#destroy"

  # Flights:
  get   "/flights/new-flight-menu/(trip/:trip_id)" => "flights#new_flight_menu", as: :new_flight_menu
  post  "/flights/new-flight-menu/(trip/:trip_id)" => "flights#change_trip",    as: :change_new_flight_trip
  match "/flights/new/"                            => "flights#new", via: [:get, :post], as: :new_flight
  get   "/flights(/:map_id.:extension)" => "flights#index"
  resources :flights, except: [:index, :new]
  get   "/flights/:id(/:map_id.:extension)"        => "flights#show"
  get   "/flights/from/:start_date/to/:end_date(/:map_id.:extension)"   => "flights#show_date_range",  as: :show_date_range
  get   "/flights/year/:year(/:map_id.:extension)" => "flights#show_date_range", as: :show_year

  # Trips:
  resources :trips, except: [:show]
  get   "/trips/:id(/:map_id.:extension)"          => "trips#show"
  get   "/trips/:trip/section/:section(/:map_id.:extension)" => "trips#show_section", as: :show_section

  # Airports:
  get   "/airports(/:map_id.:extension)"     => "airports#index"
  resources :airports, except: [:index, :show]
  get   "/airports/:id(/:map_id.:extension)" => "airports#show"

  # Airlines and operators:
  resources :airlines
  get   "/airlines/:id(/:map_id.:extension)" => "airlines#show"
  get   "/operators/:operator(/:map_id.:extension)" => "airlines#show_operator", as: :show_operator
  get   "/operators/:operator/:fleet_number(/:map_id.:extension)" => "airlines#show_fleet_number", as: :show_fleet_number

  # Aircraft families and types:
  get   "/aircraft/new(/family/:family_id)"    => "aircraft_families#new",      as: :new_aircraft_family
  resources :aircraft_families, path: :aircraft, except: [:new]
  get   "/aircraft/:id(/:map_id.:extension)" => "aircraft_families#show"

  # Travel classes:
  get   "/classes"                           => "flights#index_classes"
  get   "/classes/:travel_class(/:map_id.:extension)" => "flights#show_class",  as: :show_class

  # Tail numbers:
  get   "/tails"                             => "flights#index_tails"
  get   "/tails/:tail_number(/:map_id.:extension)" => "flights#show_tail",      as: :show_tail

  # Flight routes:
  resources :routes, only: [:update]
  get   "/routes"                            => "routes#index"
  get   "/routes/:airport1/:airport2(/:map_id.:extension)" => "routes#show",    as: :show_route
  get   "/routes/edit/:airport1/:airport2"   => "routes#edit",                  as: :edit_route
  get   "/routes/:route" => redirect("routes", status: 301) # Redirect legacy routes to Index Routes

  # Boarding pass import pages:
  resources :p_k_passes, only: [:destroy]

  # Boarding pass parser pages:
  get   "/boarding-pass" => "flights#input_boarding_pass"
  get   "/boarding-pass/build" => "flights#build_boarding_pass", as: :build_boarding_pass
  get   "/boarding-pass/results/:data" => "flights#show_boarding_pass", as: :show_boarding_pass
  get   "/boarding-pass/json(/:callback)/:data" => "flights#show_boarding_pass_json", as:
   :show_boarding_pass_json

  # Admin pages:
  get   "/admin"                         => "admin#admin", as: :admin
  get   "/admin/airport-first-visits"    => "admin#airport_first_visits",    as: :airport_first_visits
  get   "/admin/annual-summary"          => "admin#annual_flight_summary",   as: :annual_flight_summary
  get   "/admin/boarding-pass-validator" => "admin#boarding_pass_validator", as: :boarding_pass_validator

  # API:
  get "api" => "api#index"
  get "api/annual_flight_summary"
  get "api/all_flights"
  get "api/recent_flights"

  # Certbot:
  get "/.well-known/acme-challenge/:id" => "pages#letsencrypt"

end

app/views/pages/flightlog.html.erb
<p>In 2009, I started traveling frequently for work. Not long after that, I began to document <%= link_to("every airline and charter flight", flights_path) %> Iʼd taken. This flight log takes all of that data, and makes maps and tables out of it.</p>

<% if @flights.empty? %>
  <%= render partial: "flights/error_no_flights" %>
<% end %>

<%= render(partial: "layouts/map", locals: {map: @maps[:flights_map],  metrics: {flights: @flights.size, flights_path: flights_path, miles: @total_distance}}) %>

<% if @flights.any? %>
<div class="center">

<div class="intro-box column">
  <h2>Top Airports</h2>
  <table class="flightlog" id="top-airports-table">
    <tr>
      <th class="left">City</th>
      <th class="center">Code</th>
      <th class="center">Visits</th>
    </tr>
  <% @flight_airports.first(5).each do |airport| %>
    <tr id="airport-count-row-<%= airport[:id] %>">
      <td class="left"><%= country_flag_icon(airport[:country]) %> <%= link_to(airport[:city], airport_path(airport[:slug]), title: "View airport details for #{airport[:city]}") %></td>
      <td class="center code-mono"><%= link_to(airport[:iata_code], airport_path(airport[:slug]), title: "View airport details for #{airport[:city]}") %></td>
      <td class="center"><%= airport[:visit_count] %></td>
    </tr>
  <% end %>
  </table>
  <p><%= link_to(ActiveSupport::SafeBuffer.new + "See all " + content_tag(:span, pluralize(NumberFormat.value(@flight_airports.size), "airport"), class: "summary-total"), airports_path) %></p>
</div>

<div class="intro-box column">
  <h2>Top Airlines</h2>
  <table class="flightlog" id="top-airlines-table">
    <tr>
      <th class="left">Airline</th>
      <th class="center">Flights</th>
    </tr>
  <% @flight_airlines.first(5).each do |airline| %>
    <tr id="airline-count-row-<%= airline[:id] %>">
      <td class="left">
      <%= link_to(airline_icon(airline[:slug], title: airline[:name]) + airline[:name], airline_path(airline[:slug]), title: "View flights on #{airline[:name]}") %></td>
      <td class="center"><%= airline[:flight_count] %></td>
    </tr>
  <% end %>
  </table>
  <p><%= link_to(ActiveSupport::SafeBuffer.new + "See all " + content_tag(:span, pluralize(NumberFormat.value(@flight_airlines.size), "airline"), class: "summary-total"), airlines_path) %></p>
</div>

<div class="intro-box column">
  <h2>Top Routes</h2>
  
  <table class="flightlog" id="top-routes-table">
    <tr>
      <th class="left">Route</th>
      <th class="center">Flights</th>
    </tr>
  <% @flight_routes.first(5).each do |flight_route| %>
    <tr id="route-count-row-<%= flight_route[:route].pluck(:slug).sort.join("-to-") %>">
      <td class="left"><%= link_to(format_route(flight_route[:route].map{|r| r.iata_code}), show_route_path(airport1: flight_route[:route].first.slug, airport2: flight_route[:route].last.slug), title: "View flights between #{flight_route[:route][0].city} and #{flight_route[:route][1].city}") %></td>
      <td class="center"><%= flight_route[:flight_count] %></td>
    </tr>
  <% end %>
  </table>
  <p><%= link_to(ActiveSupport::SafeBuffer.new + "See all " + content_tag(:span, pluralize(NumberFormat.value(@flight_routes.size), "route"), class: "summary-total"), routes_path) %></p>
</div>

<div class="intro-box column">
  <h2>Top Aircraft</h2>
  
  <table class="flightlog" id="top-aircraft-table">
    <tr>
      <th class="left">Aircraft Family</th>
      <th class="center">Flights</th>
    </tr>
    <% @flight_aircraft.first(5).each do |aircraft| %>
      <tr id="aircraft-family-count-row-<%= aircraft[:id] %>">
        <td class="left"><%= link_to(format_aircraft_family(aircraft[:manufacturer], aircraft[:name]), aircraft_family_path(aircraft[:slug]), title: "View flights on #{aircraft[:name]} aircraft") %></td>
        <td class="center"><%= aircraft[:flight_count] %></td>
      </tr>
    <% end %>
  </table>
  <p><%= link_to(ActiveSupport::SafeBuffer.new + "See all " + content_tag(:span, pluralize(NumberFormat.value(@flight_aircraft.size), "aircraft family"), class: "summary-total"), aircraft_families_path) %></p>
</div>

<div class="intro-box column">
  <h2>Top Tails</h2>
  <table class="flightlog" id="top-tail-numbers-table">
    <tr>
      <th class="left">Tail Number</th>
      <th class="center">Flights</th>
  <% @flight_tails.first(5).each do |tail| %>
    <tr id="tail-number-count-row-<%= tail[:tail_number] %>">
      <td class="left tail-number"><%= tail_number_with_country_flag(tail[:tail_number]) %></td>
      <td class="center"><%= tail[:count] %></td>
    </tr>
  <% end %>
  </table>
  <p><%= link_to(ActiveSupport::SafeBuffer.new + "See all " + content_tag(:span, pluralize(NumberFormat.value(@flight_tails.size), "tail number"), class: "summary-total"), tails_path) %></p>
</div>

</div>

<div class="center">

<% if @route_superlatives || logged_in? %>	
<div class="intro-box column">
  <h2>Superlatives</h2>
	<%= render partial: "routes/route_superlatives_table", locals: {superlatives: @route_superlatives} %>
</div>
<% end %>

</div>
<% end %>

<p class="center">Flights from trips in progress are not shown until the trip is complete.</p>
<p class="pre-footer">
  <%= link_to("How I made the Flight Historian", "https://paulbogard.net/flight-historian/", target: "_blank")%> &emsp; 
  <%= link_to("Boarding Pass Parser", boarding_pass_path)%>
</p>