config/routes.rb
Portfolio::Application.routes.draw do

  root "pages#flightlog"
  get "/:map_id.:extension" => "pages#flightlog", as: :root_path

  # Users:
  resources :users

  # Sessions:
  resources :sessions, only: [:new, :create, :destroy]
  get    "/signup" => "users#new"
  get    "/login"  => "sessions#new"
  delete "/logout" => "sessions#destroy"

  # Flights:
  get   "/flights/new-flight-menu/(trip/:trip_id)" => "flights#new_flight_menu", as: :new_flight_menu
  post  "/flights/new-flight-menu/(trip/:trip_id)" => "flights#change_trip",    as: :change_new_flight_trip
  match "/flights/new/"                            => "flights#new", via: [:get, :post], as: :new_flight
  get   "/flights(/:map_id.:extension)" => "flights#index"
  resources :flights, except: [:index, :new]
  get   "/flights/:id(/:map_id.:extension)"        => "flights#show"
  get   "/flights/from/:start_date/to/:end_date(/:map_id.:extension)"   => "flights#show_date_range",  as: :show_date_range
  get   "/flights/year/:year(/:map_id.:extension)" => "flights#show_date_range", as: :show_year

  # Trips:
  resources :trips, except: [:show]
  get   "/trips/:id(/:map_id.:extension)"          => "trips#show"
  get   "/trips/:trip/section/:section(/:map_id.:extension)" => "trips#show_section", as: :show_section

  # Airports:
  get   "/airports(/:map_id.:extension)"     => "airports#index"
  resources :airports, except: [:index, :show]
  get   "/airports/:id(/:map_id.:extension)" => "airports#show"

  # Airlines and operators:
  resources :airlines
  get   "/airlines/:id(/:map_id.:extension)" => "airlines#show"
  get   "/operators/:operator(/:map_id.:extension)" => "airlines#show_operator", as: :show_operator
  get   "/operators/:operator/:fleet_number(/:map_id.:extension)" => "airlines#show_fleet_number", as: :show_fleet_number

  # Aircraft families and types:
  get   "/aircraft/new(/family/:family_id)"    => "aircraft_families#new",      as: :new_aircraft_family
  resources :aircraft_families, path: :aircraft, except: [:new]
  get   "/aircraft/:id(/:map_id.:extension)" => "aircraft_families#show"

  # Travel classes:
  get   "/classes"                           => "flights#index_classes"
  get   "/classes/:travel_class(/:map_id.:extension)" => "flights#show_class",  as: :show_class

  # Tail numbers:
  get   "/tails"                             => "flights#index_tails"
  get   "/tails/:tail_number(/:map_id.:extension)" => "flights#show_tail",      as: :show_tail

  # Flight routes:
  resources :routes, only: [:update]
  get   "/routes"                            => "routes#index"
  get   "/routes/:airport1/:airport2(/:map_id.:extension)" => "routes#show",    as: :show_route
  get   "/routes/edit/:airport1/:airport2"   => "routes#edit",                  as: :edit_route
  get   "/routes/:route" => redirect("routes", status: 301) # Redirect legacy routes to Index Routes

  # Boarding pass import pages:
  resources :p_k_passes, only: [:destroy]

  # Boarding pass parser pages:
  get   "/boarding-pass" => "flights#input_boarding_pass"
  get   "/boarding-pass/build" => "flights#build_boarding_pass", as: :build_boarding_pass
  get   "/boarding-pass/results/:data" => "flights#show_boarding_pass", as: :show_boarding_pass
  get   "/boarding-pass/json(/:callback)/:data" => "flights#show_boarding_pass_json", as:
   :show_boarding_pass_json

  # Admin pages:
  get   "/admin"                         => "admin#admin", as: :admin
  get   "/admin/airport-first-visits"    => "admin#airport_first_visits",    as: :airport_first_visits
  get   "/admin/annual-summary"          => "admin#annual_flight_summary",   as: :annual_flight_summary
  get   "/admin/boarding-pass-validator" => "admin#boarding_pass_validator", as: :boarding_pass_validator

  # API:
  get "api" => "api#index"
  get "api/annual_flight_summary"
  get "api/all_flights"
  get "api/recent_flights"

  # Certbot:
  get "/.well-known/acme-challenge/:id" => "pages#letsencrypt"

end

app/views/layouts/_admin_panel.html.erb
<% if logged_in? %>
<div id="user-footer">
  <span class="bold"><%= current_user.name %></span> &emsp; <%= link_to "Admin", admin_path %> &emsp; <%= link_to "Log out", logout_path, :method => :delete %>
  
</div>
<% end %>

app/views/layouts/_breadcrumbs.html.erb
<% if (!(params[:controller] == "pages" && params[:action] == "flightlog") && (@breadcrumbs || (logged_in? && @admin_actions.present?))) %>

  <div id="breadcrumbs-and-admin-actions">
    
    <% if @breadcrumbs && @breadcrumbs.any? %>
      <% @breadcrumbs[0..-2].uniq.each do |txt, path| %>
        <%= link_to(h(txt), path) %> <span class="breadcrumb-separator">▸</span> 
      <% end %>
      <span class="breadcrumb-title"><%= h(@breadcrumbs.last.first) %></span>
    <% else %>
      &nbsp;
    <% end %>

    <% if (logged_in? && @admin_actions.present?) %>
    <div id="admin-actions">
      <%= safe_join(@admin_actions, sanitize("&emsp;")) %>
    </div>
    <% end %>

  </div>

<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer">
    Flight Historian created by and &copy; <%= Time.now.year %> <%= link_to "Paul Bogard", "https://paulbogard.net/", target: "_blank" %>.<br>Source code is availble in a <%= link_to("GitHub repository", "https://github.com/bogardpd/flight_log", target: :_blank) %> under the MIT license.
    <% if @logo_used %>
      <div>The airline logos used on this page are trademarks of their respective airlines. It is believed that the use of these logos qualifies as nominative fair use under United States trademark law.</div>
    <% end %>
  </div>  
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="header">
    <% logo = image_tag("logo.svg", :class => "logo", :alt => "Paul Bogardʼs Flight Historian") %>
    <%= link_to logo, root_path %>
    <div id="portfolio-link">
      by <%= link_to("Paul Bogard", "https://paulbogard.net/", title: "Paul Bogard", target: "_blank") %>
    </div>
  </div>
</header>

app/views/layouts/_map.html.erb
<% mapboxgl_attr = map.mapboxgl %>
<% map_id = mapboxgl_attr[:id] %>
<div class="inset <%= mapboxgl_attr[:map_type] %>" id="<%= mapboxgl_attr[:id] %>">

  <% if local_assigns[:metrics] %>
  <%= render(partial: "layouts/personal_metrics", locals: {map: map, metrics: metrics}) %>
  <% end %>

  <div class="map-mapbox" id="mapbox_<%= map_id %>"></div>
  
  <div class="map-download-links">
    <%= link_to("GPX", params.permit!.merge(map_id: mapboxgl_attr[:id], extension: :gpx), download: "#{mapboxgl_attr[:id]}.gpx") %>
    &middot; 
    <%= link_to("KML", params.permit!.merge(map_id: mapboxgl_attr[:id], extension: :kml), download: "#{mapboxgl_attr[:id]}.kml") %>
    &middot; 
    <%= link_to("GeoJSON", params.permit!.merge(map_id: mapboxgl_attr[:id], extension: :geojson), download: "#{mapboxgl_attr[:id]}.geojson") %>
    &middot; 
    <%= link_to("GraphML", params.permit!.merge(map_id: mapboxgl_attr[:id], extension: :graphml), download: "#{mapboxgl_attr[:id]}.graphml") %>
    <% if map.gcmap_exists? %>
    &middot;
    <%= link_to("GCMap", map.gcmap_url) %>
    <% end %>
  </div>

</div>

<script>
  const map_data_<%= map_id %> = <%= map.geojson.html_safe %>;
  const map_type_<%= map_id %> = '<%= mapboxgl_attr[:map_type] %>';
  populateMapboxGLMap('<%= map_id %>', map_data_<%= map_id %>, map_type_<%= map_id %>);
</script>

app/views/layouts/_message.html.erb
<div class="message message-<%= message[:type] %>" id="<%= message[:id] %>"><%= sanitize(message[:text]) %></div>

app/views/layouts/_navigation.html.erb
<nav>
  <div id="menu">
    <div class="menu-home">
      <ul>
        <% if (params[:controller] == "pages" && params[:action] == "flightlog") %>
          <li class="active"><a class="active_non_link">Home</a></li>
        <% else %>
          <li><%= link_to("Home", root_path, :title => "View the home page of Paul Bogardʼs Flight Log") %></li>
        <% end %>
      </ul>
    </div>
    <div class="menu-main">
      <ul>
        
        <% if (params[:controller] == "flights" && params[:action] == "index" && params[:year].blank? && params[:start_date].blank? && params[:end_date].blank?) %>
          <li class="active"><a class="active_non_link">Flights</a></li>
        <% elsif (params[:controller] == "flights" && (params[:action] == "show" || params[:year].present? || params[:start_date].present? || params[:end_date].present?)) %>
          <li class="active"><%= link_to("Flights", flights_path, :title => "View a list of Paulʼs flights", :class => "active")%></li>
        <% else %>
          <li><%= link_to("Flights", flights_path, :title => "View a list of Paulʼs flights")%></li>
        <% end %>

        <% if (params[:controller] == "routes" && params[:action] == "index") %>
          <li class="active"><a class="active_non_link">Routes</a></li>
        <% elsif (params[:controller] == "routes" && params[:action] == "show") %>
          <li class="active"><%= link_to("Routes", routes_path, :title => "View a list of the routes Paul has flown", :class => "active")%></li>
        <% else %>
          <li><%= link_to("Routes", routes_path, :title => "View a list of the routes Paul has flown")%></li>
        <% end %>
        
        <% if (params[:controller] == "airports" && params[:action] == "index") %>
          <li class="active"><a class="active_non_link">Airports</a></li>
        <% elsif (params[:controller] == "airports" && params[:action] == "show") %>
          <li class="active"><%= link_to("Airports", airports_path, :title => "View a list of airports Paul has visited", :class => "active")%></li>
        <% else %>
          <li><%= link_to("Airports", airports_path, :title => "View a list of airports Paul has visited")%></li>
        <% end %>
        
        <% if (params[:controller] == "aircraft_families" && params[:action] == "index") %>
        	<li class="active"><a class="active_non_link">Aircraft</a></li>
        <% elsif (params[:controller] == "aircraft_families" && params[:action] == "show") %>
        	<li class="active"><%= link_to("Aircraft", aircraft_families_path, :title => "View a list of the types of planes on which Paul has flown", :class => "active")%></li>
        <% else %>
        	<li><%= link_to("Aircraft", aircraft_families_path, :title => "View a list of the types of planes on which Paul has flown")%></li>
        <% end %>
        
        <% if (params[:controller] == "airlines" && params[:action] == "index") %>
        <li class="active"><a class="active_non_link">Airlines</a></li>
        <% elsif (params[:controller] == "airlines" && ["show", "show_operator", "show_fleet_number"].include?(params[:action])) %>
        <li class="active"><%= link_to("Airlines", airlines_path, :title => "View a list of the airlines on which Paul has flown", :class => "active")%></li>
        <% else %>
        <li><%= link_to("Airlines", airlines_path, :title => "View a list of the airlines on which Paul has flown")%></li>
        <% end %>
        
        <% if (params[:controller] == "flights" && params[:action] == "index_tails") %>
        <li class="active"><a class="active_non_link">Tails</a></li>
        <% elsif (params[:controller] == "flights" && params[:action] == "show_tail") %>
        <li class="active"><%= link_to("Tails", tails_path, :title => "View how many flights Paul has flown on each individual airplane", :class => "active")%></li>
        <% else %>
        <li><%= link_to("Tails", tails_path, :title => "View how many flights Paul has flown on each individual airplane")%></li>
        <% end %>
        
        <% if (params[:controller] == "flights" && params[:action] == "index_classes") %>
        <li class="active"><a class="active_non_link">Classes</a></li>
        <% elsif (params[:controller] == "flights" && params[:action] == "show_class") %>
        <li class="active"><%= link_to("Classes", classes_path, :title => "View how many flights Paul has flown in each class", :class => "active")%></li>
        <% else %>
        <li><%= link_to("Classes", classes_path, :title => "View how many flights Paul has flown in each class")%></li>
        <% end %>
        
        <% if (params[:controller] == "trips" && params[:action] == "index") %>
        <li class="active"><a class="active_non_link">Trips</a></li>
        <% elsif (params[:controller] == "trips" && (params[:action] == "show" || params[:action] = "show_section")) %>
        <li class="active"><%= link_to("Trips", trips_path, :title => "View a list of trips Paul has taken", :class => "active")%></li>
        <% else %>
        <li><%= link_to("Trips", trips_path, :title => "View a list of trips Paul has taken")%></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_personal_metrics.html.erb
<% if local_assigns[:map].nil? %>
<div class="inset">
<div class="personal-metrics personal-metrics-nomap">
<% else %>
<div class="personal-metrics">
<% end %>
  <div class="personal-metric personal-metric-label">Paul’s<br>stats:</div>

  <% if metrics[:custom] %><% metrics[:custom].each do |key, value| %>
  <div class="personal-metric">
    <span class="personal-metric-number"><%= NumberFormat.value(value) %></span><br>
    <%# Pluralize words in the key that end in "(s)". %>
    <% words = key.to_s.split(" ") %>
    <%= words.map{|w| w[-3,3] == "(s)" ? w[0..-4].pluralize(value) : w}.join(" ") %>
  </div>
  <% end %><% end %>

  <% if metrics[:flights] %>
  <div class="personal-metric">
    <span class="personal-metric-number flights-count" data-flights="<%= metrics[:flights] %>"><%= NumberFormat.value(metrics[:flights]) %></span><br>
    <% if metrics[:flights_path] %><a href="<%= url_for(metrics[:flights_path]) %>"><% end %>
    <%= "flight".pluralize(metrics[:flights]) %>
    <% if metrics[:flights_path] %></a><% end %>
  </div>
  <% end %>

  <% if metrics[:miles] %>
  <div class="personal-metric">
    <span class="personal-metric-number distance-mi"><%= NumberFormat.value(metrics[:miles]) %></span><br>
    <%= [metrics[:adjective],"mile"].compact.join(" ").pluralize(metrics[:miles]) %>
  </div>
  <div class="personal-metric">
    <span class="personal-metric-number distance-km"><%= NumberFormat.value(Distance::km(metrics[:miles])) %></span><br>
    <%= [metrics[:adjective],"kilometer"].compact.join(" ").pluralize(Distance::km(metrics[:miles])) %>
  </div>
  <% end %>

</div>
<% if local_assigns[:map].nil? %></div><% end %>

app/views/layouts/_summary.html.erb
<% counts ||= Hash.new %>
<% summary_items ||= Hash.new %>

<% if summary_items.any? %>
  <table class="summary">
    <tr>
      <% summary_items.keys.each do |title| %>
        <th><%= title %></th>
      <% end %>
    </tr>
    <tr>
      <% summary_items.each do |title, value| %>
        <td id="summary-value-<%= title.to_s.parameterize %>"><%= value %></td>
      <% end %>
    </tr>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" prefix="og: https://ogp.me/ns#">
<head>
  <% meta = page_metadata %>
  <!-- Created by Paul Bogard. https://github.com/bogardpd/flight_log -->

  <title><%= meta[:title_and_site] %></title>
  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="icon" href="/favicon.ico" />
	<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	<link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:400&text=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600" rel="stylesheet" type="text/css">
	<%= stylesheet_link_tag "application", :media => "all" %>
  <meta name="viewport" content="width=820, user-scalable=yes" />
  <meta name="format-detection" content="telephone=no">
  <meta charset="utf-8">
  
  <%= csrf_meta_tag %>
  <%= javascript_include_tag :application %>

  <!-- Mapbox -->
  <script src="https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.js"></script>
  <link href="https://api.mapbox.com/mapbox-gl-js/v3.4.0/mapbox-gl.css" rel="stylesheet" />
  <script>
    mapboxgl.accessToken = '<%= Rails.env.development? ? Rails.application.credentials[:mapbox][:api_key][:unrestricted] : Rails.application.credentials[:mapbox][:api_key][:flight_historian] %>';
  </script>

  <!-- Open Graph/Metadata -->
  <meta name="author" content="Paul Bogard">
  <meta name="description" content="<%= meta[:description] %>">
  <meta property="og:site_name" content="<%= meta[:site_name] %>">
  <meta property="og:title" content="<%= meta[:title] %>">
  <meta property="og:description" content="<%= meta[:description] %>">
  <meta property="og:type" content="website">
  <meta property="og:url" content="<%= meta[:url] %>">
  <meta property="og:image" content="<%= meta[:image] %>">
  <meta property="og:locale" content="en_US">

  <%= yield :head_includes %>
  
</head>
<body>

  <div id="top-banner">
  </div>
  
  <div id="menu-banner">
  </div>

  <div id="container">

    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/navigation" %>
    <%= render partial: "layouts/breadcrumbs" %>
    
    <div id="body">
          
      <%= render_messages %>
      
      <section>
        <!-- Begin page-specific body -->
        
        <%= yield %>
        
        <!-- End page-specific body -->
        
        <div class="clear"><!-- Empty div to clear floats before footer --></div>
      </section>
    </div>
    
    <%= render partial: "layouts/admin_panel" %>
    <%= render partial: "layouts/footer" %>
    
    <%= debug(params) if Rails.env.development? %>
  </div>


</body>
</html>